[tools]
"asdf:richin13/asdf-neovim" = "latest"
gh = "latest"
node = "24"
zoxide = "latest"
fzf = "latest"
zellij = "latest"
starship = "latest"
lazygit = "latest"
lazydocker = "latest"
lsd = "latest"
yazi = "latest"
ripgrep = "latest"
opencode = "latest"
