[tools]
"cargo:broot" = "latest"
"cargo:procs" = "latest"
"cargo:xcp" = "latest"
bat = "latest"
dust = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
neovim = "latest"
node = "24"
opencode = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
